server:
  port: 8701 # 服务提供方
  tomcat:
    uri-encoding: UTF-8
# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8699/eureka
  instance:
    hostname: localhost
banner:
  charset: UTF-8

spring:
  #当前服务名称
  application:
    name: eureka-service
  #数据源
  datasource:
    #    type: org.apache.commons.dbcp.BasicDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/yunbase?&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    #    username: root
    #    password: 123
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://148.70.66.147:3306/yunbase?&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ayp43520
  #  resources:
  #    static-locations: classpath:/resources/,classpath:/static/
  #freemarker静态资源配置
  freemarker:
    #template-loader-path: classpath:/templates
    #关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    #设定ftl文件路径
    suffix: .html
    settings:
      template_update_delay: 10
  messages:
    encoding: UTF-8
  http:
    multipart:
      max-request-size: 209715200
      max-file-size: 209715200    #用来控制默认上传文件的大小  这里的单位是字节  这里的配置是200m
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mail:
    host: smtp.qq.com
    username: ayp199645aabb@qq.com
    password: ettdtxuejgvsbahj
    properties:
      mail:
        smtp:
          auth: true
          timeout: 25000
mybatis:
  mapper-locations: classpath:com/yun/dao/*.xml
  type-aliases-package: com.yun.entity