server:
  port: 8701 # 服务提供方

# 指定当前eureka客户端的注册地址,
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8699/eureka
  instance:
    hostname: localhost


spring:
  #当前服务名称
  application:
    name: eureka-service
  #数据源
  datasource:
    type: org.apache.commons.dbcp.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yunbase?&useSSL=false
    username: root
    password: 123
  resources:
    static-locations: classpath:/resources/,classpath:/static/
  #freemarker静态资源配置
  freemarker:
    template-loader-path: classpath:/templates
    #关闭缓存，及时刷新，上线生产环境需要修改为true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    #设定ftl文件路径
    suffix: .html
    settings:
      template_update_delay: 10

mybatis:
  mapper-locations: classpath:com/yun/dao/*.xml
  type-aliases-package: com.yun.entity

